[build]
  base = "frontend"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "frontend/build"

[build.environment]
  CI = "false"
  DISABLE_ESLINT_PLUGIN = "true"
  SKIP_PREFLIGHT_CHECK = "true"
  GENERATE_SOURCEMAP = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
