[build]
  command = "cd frontend && npm install --legacy-peer-deps && npm run build"
  publish = "frontend/build"

[build.environment]
  CI = "false"
  DISABLE_ESLINT_PLUGIN = "true"
  SKIP_PREFLIGHT_CHECK = "true"
  GENERATE_SOURCEMAP = "false"
  ESLINT_NO_DEV_ERRORS = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
